# Generated by Django 4.1.3 on 2022-12-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiosession',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnosis'),
        ),
        migrations.AlterField(
            model_name='physiosession',
            name='therapy',
            field=models.ManyToManyField(default='Old Therapy', to='main.therapy'),
        ),
    ]
