# Generated by Django 4.1.3 on 2023-05-15 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_patient_first_name_remove_patient_patient_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physiosession",
            name="date",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="old_therapy",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="patient_name",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="patient_no",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="patient_surname",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="receipt_no",
        ),
    ]
