# Generated by Django 4.1.3 on 2023-05-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_physiosession_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="in_patient",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="out_patient",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="patient_type",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="sex",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="admission_no",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="patient_type",
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="gender",
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="surname",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
