# Generated by Django 4.1.3 on 2023-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_remove_patient_in_patient_remove_patient_out_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosession",
            name="admission_no",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
