# Generated by Django 4.1.3 on 2023-05-15 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_physiosession_admission_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physiosession",
            name="admission_no",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="date_of_visit",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="more_notes",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="quantity_of_sessions",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="status",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="therapist",
        ),
        migrations.RemoveField(
            model_name="physiosession",
            name="ward",
        ),
        migrations.CreateModel(
            name="PhysioSessionAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_no", models.CharField(max_length=10)),
                ("date_of_visit", models.DateField()),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("more_notes", models.TextField()),
                ("quantity_of_sessions", models.PositiveIntegerField(default=0)),
                (
                    "diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.diagnosis"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.doctor"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.patient"
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ward",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.ward",
                    ),
                ),
            ],
        ),
    ]
