# Generated by Django 4.1.3 on 2023-05-15 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_physiosession_admission_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosession",
            name="admission_no",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.physiosessionadmission",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="physiosession",
            name="more_notes",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="physiosession",
            name="therapist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
