# Generated by Django 4.1.3 on 2023-05-16 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_physiosession_physiosession_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="receipt",
            name="patient",
        ),
        migrations.AddField(
            model_name="receipt",
            name="physiosessionadmission",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.physiosessionadmission",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receipt",
            name="receipt_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
