# Generated by Django 4.1.3 on 2023-05-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_receipt_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="visit_no",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
