# Generated by Django 4.1.3 on 2023-05-19 07:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_rename_status_physiosessionadmission_discharge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosession",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="receipt",
            name="physiosessionadmission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_physiosessionadmission",
                to="main.physiosessionadmission",
            ),
        ),
    ]
