# Generated by Django 4.1.3 on 2023-05-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_alter_physiosession_admission_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physiosessionadmission",
            name="admission_no",
            field=models.CharField(max_length=255),
        ),
    ]
