# Generated by Django 4.1.3 on 2023-06-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_physiosessionadmission_admission_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosessionadmission",
            name="clinic_master_admission_no",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
