# Generated by Django 4.1.3 on 2023-06-24 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_physiosessionadmission_clinic_master_admission_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosessionadmission",
            name="discharge_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
