# Generated by Django 4.1.3 on 2023-06-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_physiosessionadmission_discharge_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physiosessionadmission",
            name="discharge_date",
            field=models.DateField(null=True),
        ),
    ]
