# Generated by Django 4.1.3 on 2023-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_alter_physiosessionadmission_discharge_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="physiosession",
            name="quantity_of_session_left",
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
